name: CI/CD with Github Action

on: [push]

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64

      - name: Compile
        run: ./gradlew classes

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build/classes
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


  Test:
    needs: [Compile]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build/classes
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test
        run: ./gradlew test
      - name: Upload testReport
        uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: build/reports/tests/test/


  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.getVersion.outputs.version }}
      name: ${{ steps.getName.outputs.name }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build/classes
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble
        run: ./gradlew jar
      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: buildedJar
          path: build/libs/

      - id: getVersion
        run: echo "::set-output name=version::$(./gradlew -q printVersion)"
      - id: getName
        run: echo "::set-output name=name::$(./gradlew -q printName)"

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Assemble]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildedJar
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ needs.Assemble.outputs.name }}-${{ needs.Assemble.outputs.version }}.jar
