name: CI/CD with Github Action

on: [push]

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.10 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64
      - name: Compile
        run: ./gradlew classes

  Test:
    needs: [Compile]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.10 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64
      - name: Test
        run: ./gradlew test
      - name: Upload testReport
        uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: build/reports/tests/test/

  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.10 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
          architecture: x64
      - name: Assemble
        run: ./gradlew jar
      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: buildedJar
          path: build/libs/
      - name: Get project version
        run: echo "::set-output name=version::$(./gradlew -q printVersion)"

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Assemble]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildedJar
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: buildedJar/st_nycu_lab4-${{ needs.Assemble.outputs.version }}.jar
